/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    CustomerNode: typeof import('./src/components/CustomerNode.vue')['default']
    ExtraButton: typeof import('./src/components/Nodes/ExtraButton.vue')['default']
    FileUploadPanel: typeof import('./src/components/FileUploadPanel.vue')['default']
    GraphToolBar: typeof import('./src/components/GraphToolBar.vue')['default']
    GuideLine: typeof import('./src/components/GuideLine.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MindMap: typeof import('./src/components/MindMap.vue')['default']
    NoteNode: typeof import('./src/components/Nodes/NoteNode.vue')['default']
    RobotMessage: typeof import('./src/components/RobotMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareCard: typeof import('./src/components/ShareCard.vue')['default']
    SingleNodeWithToolTip: typeof import('./src/components/SingleNodeWithToolTip.vue')['default']
    TopicChildNode: typeof import('./src/components/Nodes/TopicChildNode.vue')['default']
    TopicNode: typeof import('./src/components/Nodes/TopicNode.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
